---
language: node_js
node_js:
  - "6"

sudo: false
dist: trusty

cache:
  yarn: true

addons:
  code_climate:
    repo_token: 88c79d4795cce3095bb0145b329f0a2b2748f3ec4cdf11d7949363a086206560
  apt:
    packages:
      - google-chrome-stable

env:
  # we recommend testing LTS's and latest stable release (bonus points to beta/canary)
  - EMBER_TRY_SCENARIO=ember-lts-2.4
  - EMBER_TRY_SCENARIO=ember-lts-2.8
  - EMBER_TRY_SCENARIO=ember-2.12.2
  - EMBER_TRY_SCENARIO=ember-release
  - EMBER_TRY_SCENARIO=ember-beta
  - EMBER_TRY_SCENARIO=ember-canary
  - EMBER_TRY_SCENARIO=ember-default

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary
    - env: EMBER_TRY_SCENARIO=ember-beta

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn global add codeclimate-test-reporter

install:
  - yarn install --no-lockfile

script:
  # Usually, it's ok to finish the test scenario without reverting
  #  to the addon's original dependency state, skipping "cleanup".
  - HEADLESS=true node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO test --skip-cleanup

after_script:
  - codeclimate-test-reporter < coverage/lcov.info
