---
language: node_js
node_js:
  - "4"

sudo: required
dist: trusty

cache:
  directories:
    - node_modules
    - $HOME/.npm
    - $HOME/.cache # includes bowers cache

addons:
  code_climate:
    repo_token: 88c79d4795cce3095bb0145b329f0a2b2748f3ec4cdf11d7949363a086206560
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

matrix:
  fast_finish: true

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm config set spin false
  - npm install -g npm@^3
  - npm install -g bower
  - npm install -g codeclimate-test-reporter
  - bower --version

install:
  - npm install
  - bower install

script:
  - ember try:one $EMBER_VERSION --skip-cleanup=true --- ember test

env:
  matrix:
    - EMBER_VERSION=ember-lts-2.4
    - EMBER_VERSION=ember-lts-2.8
    - EMBER_VERSION=ember-release
    - EMBER_VERSION=ember-beta
    - EMBER_VERSION=ember-canary

matrix:
  allow_failures:
    - env: EMBER_VERSION=ember-canary
    - env: EMBER_VERSION=ember-beta

after_script:
  - codeclimate-test-reporter < coverage/lcov.info
